const Document = require('../models/Document');
const Message = require('../models/Message');

/**
 * Builds a comprehensive Markdown intelligence report for a document and its conversation.
 * @param {string} documentId
 * @param {string} [conversationId]
 * @returns {Promise<{markdown: string, title: string, generatedAt: string}>}
 */
async function generateReport(documentId, conversationId = null) {
  const doc = await Document.findById(documentId);
  if (!doc) throw new Error('Document not found');

  let chatHistory = [];
  if (conversationId) {
    chatHistory = await Message.find({ conversationId }).sort({ createdAt: 1 }).lean();
  }

  const generatedAt = new Date().toISOString().split('T')[0];
  const title = `DocuMind Intelligence Report — ${doc.originalName}`;

  let md = `# ${title}\n\n`;
  md += `> Generated by **DocuMind AI** on ${generatedAt}\n\n`;
  md += `## 📋 Document Metadata\n\n`;
  md += `- **File Name**: ${doc.originalName}\n`;
  md += `- **Pages**: ${doc.pageCount}\n`;
  md += `- **Indexed Chunks**: ${doc.chunkCount}\n`;
  md += `- **File Size**: ${(doc.fileSize / 1024).toFixed(1)} KB\n`;
  md += `- **Processing Status**: ${doc.status.toUpperCase()}\n\n`;

  if (doc.summary && doc.summary.executive) {
    md += `## 📑 Executive Summary\n\n${doc.summary.executive}\n\n`;

    if (doc.summary.keyPoints && doc.summary.keyPoints.length > 0) {
      md += `### 💡 Key Takeaways\n\n`;
      doc.summary.keyPoints.forEach((kp) => {
        md += `- ${kp}\n`;
      });
      md += `\n`;
    }

    if (doc.summary.actionItems && doc.summary.actionItems.length > 0) {
      md += `### 🎯 Action Items & Next Steps\n\n`;
      doc.summary.actionItems.forEach((item) => {
        md += `- [ ] ${item}\n`;
      });
      md += `\n`;
    }

    if (doc.summary.topics && doc.summary.topics.length > 0) {
      md += `### 🏷️ Identified Core Topics\n\n`;
      md += doc.summary.topics.map((t) => `\`#${t}\``).join(' ') + `\n\n`;
    }
  }

  if (chatHistory.length > 0) {
    md += `## 💬 Q&A Session Log\n\n`;
    chatHistory.forEach((msg, idx) => {
      if (msg.role === 'user') {
        md += `### Q${Math.floor(idx / 2) + 1}: ${msg.content}\n\n`;
      } else if (msg.role === 'assistant') {
        md += `**Answer:**\n\n${msg.content}\n\n`;
        if (msg.citations && msg.citations.length > 0) {
          md += `*Sources Cited:*\n`;
          msg.citations.forEach((c) => {
            md += `- Page ${c.pageNumber} (${(c.score * 100).toFixed(1)}% relevance)\n`;
          });
          md += `\n`;
        }
        md += `---\n\n`;
      }
    });
  }

  return {
    markdown: md,
    title,
    generatedAt,
    document: {
      id: doc._id,
      name: doc.originalName,
      pageCount: doc.pageCount,
    },
  };
}

module.exports = {
  generateReport,
};
